### PR TITLE
Fix date of birth formatting in AddCommand's message usage

### LINKED ISSUE #142: Example in add command's message usage is wrong for date of birth
Output from inputting `help add`:
```
add: Adds a person to the address book. Parameters: n/NAME p/PHONE e/EMAIL a/ADDRESS dob/DATE_OF_BIRTH [pri/PRIORITY = LOW] [income/INCOME = 0] [famsize/FAMILY_SIZE = 1] [r/REMARK] [t/TAG]...
Example: add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 dob/9 Mar 1999 pri/HIGH income/2000 famsize/3 r/Promises to pay back next week. t/friends t/owesMoney
```

The `dob/` parameter should follow `YYYY-MM-dd` and hence the example should instead show `dob/1999-03-09`

### PR DESCRIPTION
**Pull request by LeongWZ**
Closes #142.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -44,7 +44,7 @@ public class AddCommand extends Command {
             + PREFIX_PHONE + "98765432 "
             + PREFIX_EMAIL + "johnd@example.com "
             + PREFIX_ADDRESS + "311, Clementi Ave 2, #02-25 "
-            + PREFIX_DATE_OF_BIRTH + "9 Mar 1999 "
+            + PREFIX_DATE_OF_BIRTH + "1999-03-09"
```
Comment (Gra7ityIC3) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: There should be a space after `1999-03-09`.

**Review by Gra7ityIC3 — APPROVED** [review]
LGTM!
