### PR TITLE
Fix duplicate indexes to be parsed as unique indexes for delete command

### LINKED ISSUE #96: Deleting duplicate indexes fails silently
If the user enters the same index multiple times when deleting, e.g., `delete 6, 6, 6`, the person at index 6 is deleted but no error message is shown on the UI when the application tries to delete the same index again. Moreover, the deletion doesn't persist since it requires all deletions to be successful.

### PR DESCRIPTION
**Pull request by nws321**
This pull request will ensure that if the input for indexes for delete command have duplicates, it would still delete the persons at the unique index values inputted. This means if "delete 1,3,6,6,6" is inputted, persons at index 1,3 and 6 would be deleted. Closes #96.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -18,20 +20,36 @@ public class DeleteCommandParser implements Parser<DeleteCommand> {
...
+            String[] newArr = new String[uniqueSize];
+            Index[] uniqueIndex = new Index[uniqueSize];
 
-            for (int i = 0; i < size; i++) {
-                indexes[i] = ParserUtil.parseIndex(arr[i]);
+            for (int i = 0; i < uniqueSize; i++) {
+                newArr[i] = String.valueOf(uniqueIntArr[i]);
+            }
+            for (int i = 0; i < uniqueSize; i++) {
+                uniqueIndex[i] = ParserUtil.parseIndex(newArr[i]);
```
Comment (arjun2598) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: Perhaps this line could be combined into the above for loop, so that we only need to run the for loop once? Combining the two lines into one statement could also allow the uniqueIndex array to be created without needing the String array newArr.

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java [hunk 2]
```diff
@@ -18,20 +20,36 @@ public class DeleteCommandParser implements Parser<DeleteCommand> {
...
                     throw new ParseException(
                             String.format(MESSAGE_INVALID_COMMAND_FORMAT, DeleteCommand.MESSAGE_USAGE));
                 }
             }
-            Index[] indexes = new Index[size];
+            //convert string indexes to int indexes and sort int indexes in ascending order
+            for (int i = 0; i < inputSize; i++) {
+                intArr[i] = Integer.parseInt(inputArr[i].trim());
+            }
+            Arrays.sort(intArr);
```
Comment (arjun2598) [inline src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: Does the indexes need to be sorted for the delete command to work properly?

**Review by arjun2598 — APPROVED** [review]
LGTM, just some doubts to clear.

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java (hunk 1 above)
Comment (nws321) [reply src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: thnks for pointing this out I have pushed this change

File: src/main/java/seedu/address/logic/parser/DeleteCommandParser.java (hunk 2 above)
Comment (nws321) [reply src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: it will still delete accordingly without sorting but I sort so that the message printed abt each deleted person is in ascending order, wdyt abt this?

Comment (Gra7ityIC3) [reply src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: Is the sorting necessary or should we preserve the order of the deletions?

Comment (nws321) [reply src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: I thought it would be good to maintain the order of the priority as well in the case they delete a medium followed by high priority person. But if yall think its not necessary ill just delete the sort line.

Comment (TerenceWongsExtravaganza) [reply src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: I feel that it is better to preserve the order of deletions so that the user ill not be disorientated or confused when they see like the order of message printed and the order of their deletion does not match.

Comment (nws321) [reply src/main/java/seedu/address/logic/parser/DeleteCommandParser.java]: Noted ive removed the sort.
