### PR TITLE
Add family size field in Person model and fix DateOfBirth lowercase input

### LINKED ISSUE #99: Add family size and updated at fields in Person model
Tasks
- [X] Add family size field on Person model (PR #100)
- [X] Add updated at field on Person model (PR #104)

### LINKED ISSUE #103: Date of birth input with months in lowercase are not accepted by add and edit commands
The following commands do not work:
- `edit 1 dob/ 1 jun 2019`
- `add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 dob/18 jun 1999`

### PR DESCRIPTION
**Pull request by LeongWZ**
Partially resolves #99 and closes #103.

With the `familysize` field, we can now include people's income using the familysize/FAMILY_SIZE parameter. The default value of this field is set to 1.

The `familySize` field in `Person` class is represented by a `FamilySize` class which stores the income value as an `int`. `FamilySize` class constructor accepts strings of **positive** integers, e.g. `1`, `10`.

The updated command format is `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS dob/DATE_OF_BIRTH [pri/PRIORITY = LOW] [income/INCOME = 0] [familysize/FAMILY_SIZE = 1] [r/REMARK] [t/TAG]…​`.

For example, `add n/John Doe p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25 dob/18 Jun 1999 pri/HIGH income/1234.59 familysize/8 r/Promises to pay back next week. t/friends t/owesMoney`.

This commit also fixes the issue #103 where date of births with months in lowercase are not valid, even though they are. The fix allow users to input case-insensitive inputs (e.g. `1 dec 2019`, `1 DEC 2019`, `1 dEC 2019`). The constructor in `Date` class would then ensure that the `value` string field follows consistent formatting; the previous examples would be standardised as `1 Dec 2019`.

In the future, the type of `Date`'s `value` should be changed to `LocalDate` instead of `String` as per issue #83. This is not implemented yet for compatibility reasons.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -59,9 +61,11 @@ public AddCommand parse(String args) throws ParseException {
         Remark remark = ParserUtil.parseRemark(argMultimap.getValue(PREFIX_REMARK).orElse(""));
         DateOfBirth dateOfBirth = ParserUtil.parseDateOfBirth(argMultimap.getValue(PREFIX_DATE_OF_BIRTH).get());
         Income income = ParserUtil.parseIncome(argMultimap.getValue(PREFIX_INCOME).orElse("0"));
+        FamilySize familySize = ParserUtil.parseFamilySize(argMultimap.getValue(PREFIX_FAMILY_SIZE).orElse("0"));
```
Comment (nws321) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: I think by default family size should be 1 cus it shld include the person itself even if they have no next of kin or children

File: src/main/java/seedu/address/model/person/FamilySize.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+    private final int value;
+
+    /**
+     * Constructs a {@code FamilySize}.
+     *
+     * @param size A valid size integer
+     */
+    public FamilySize(int size) {
+        checkArgument(isValidFamilySize(size), MESSAGE_CONSTRAINTS);
```
Comment (nws321) [inline src/main/java/seedu/address/model/person/FamilySize.java:22]: Is it necessary to check the isValidFamilySize condition here again since it is already being checked by the same method in ParserUtil during parsing before being allowed through to the FamilySize constructor.

File: src/main/java/seedu/address/model/person/FamilySize.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+        return Integer.toString(value);
+    }
+
+    @Override
+    public boolean equals(Object other) {
+        if (other == this) {
+            return true;
+        }
+
+        if (!(other instanceof FamilySize otherFamilyDate)) {
```
Comment (nws321) [inline src/main/java/seedu/address/model/person/FamilySize.java]: Is the otherFamilyDate necessary? Also if it is should it be otherFamilySize instead?

**Review by nws321 — COMMENTED** [review]
LGTM just a few queries and minor things to change

File: src/main/java/seedu/address/model/person/FamilySize.java (hunk 3 above)
Comment (LeongWZ) [reply src/main/java/seedu/address/model/person/FamilySize.java]: Thanks for spotting out the typo

File: src/main/java/seedu/address/model/person/FamilySize.java (hunk 2 above)
Comment (LeongWZ) [reply src/main/java/seedu/address/model/person/FamilySize.java:22]: This argument check is necessary here as this constructor might be called by other classes. This check enforces the validity of the argument.

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java (hunk 1 above)
Comment (LeongWZ) [reply src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Thanks for noticing this mistake!

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 4]
```diff
@@ -59,9 +61,11 @@ public AddCommand parse(String args) throws ParseException {
         Remark remark = ParserUtil.parseRemark(argMultimap.getValue(PREFIX_REMARK).orElse(""));
         DateOfBirth dateOfBirth = ParserUtil.parseDateOfBirth(argMultimap.getValue(PREFIX_DATE_OF_BIRTH).get());
         Income income = ParserUtil.parseIncome(argMultimap.getValue(PREFIX_INCOME).orElse("0"));
+        FamilySize familySize = ParserUtil.parseFamilySize(argMultimap.getValue(PREFIX_FAMILY_SIZE).orElse("1"));
```
Comment (LeongWZ) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:64]: Hard code default string value for family size to be `"1"`

File: src/main/java/seedu/address/model/person/Date.java [hunk 5]
```diff
@@ -32,7 +34,7 @@ public abstract class Date {
      */
     public Date(String date) {
         checkArgument(isValidDate(date), MESSAGE_CONSTRAINTS);
-        value = date;
+        value = parseLocalDate(date).format(DATE_TIME_FORMATTER);
```
Comment (LeongWZ) [inline src/main/java/seedu/address/model/person/Date.java:37]: Since the `date` input string is now case-insenstive, this additional parsing ensures that the month in `value` instance field is capitalised, e.g. `20 jan 2019` becomes `20 Jan 2019`, `31 DEC 1980` becomes `31 Dec 1980`.

File: src/main/java/seedu/address/logic/parser/CliSyntax.java [hunk 6]
```diff
@@ -14,6 +14,7 @@ public class CliSyntax {
     public static final Prefix PREFIX_REMARK = new Prefix("r/");
     public static final Prefix PREFIX_DATE_OF_BIRTH = new Prefix("dob/");
     public static final Prefix PREFIX_INCOME = new Prefix("income/");
+    public static final Prefix PREFIX_FAMILY_SIZE = new Prefix("familysize/");
```
Comment (nws321) [inline src/main/java/seedu/address/logic/parser/CliSyntax.java:17]: Seems slightly long for prefix, maybe can consider shortening to "fs/".

**Review by nws321 — APPROVED** [review]
LGTM! Changes to prev given comments have been made as well, only minor remaining comments to consider.

File: src/main/java/seedu/address/logic/parser/CliSyntax.java (hunk 6 above)
Comment (LeongWZ) [reply src/main/java/seedu/address/logic/parser/CliSyntax.java:17]: I think `fs` might be too short and not intuitive enough? Perhaps I'll shorten the prefix to `famsize` in milestone 1.5.
